function SpawnRegions()
	return {
		{ name = "Muldraugh, KY", file = "media/maps/Muldraugh, KY/spawnpoints.lua" },
		{ name = "Riverside, KY", file = "media/maps/Riverside, KY/spawnpoints.lua" },
		{ name = "Rosewood, KY", file = "media/maps/Rosewood, KY/spawnpoints.lua" },
		{ name = "West Point, KY", file = "media/maps/West Point, KY/spawnpoints.lua" },
		{ name = "InGameMaps_Main", file = "media/maps/InGameMaps_Main/spawnpoints.lua" },
		{ name = "InGameMaps_Vanilla", file = "media/maps/InGameMaps_Vanilla/spawnpoints.lua" },
		{ name = "west_point_expansion", file = "media/maps/west_point_expansion/spawnpoints.lua" },
		{ name = "west_point_expansion_map", file = "media/maps/west_point_expansion_map/spawnpoints.lua" },
		{ name = "WestPointExpansionFix", file = "media/maps/WestPointExpansionFix/spawnpoints.lua" },
		{ name = "researchbase", file = "media/maps/researchbase/spawnpoints.lua" },
		{ name = "researchbaseroad", file = "media/maps/researchbaseroad/spawnpoints.lua" },
		{ name = "NewDenver", file = "media/maps/NewDenver/spawnpoints.lua" },
		{ name = "Rosebery", file = "media/maps/Rosebery/spawnpoints.lua" },
		{ name = "Silverton", file = "media/maps/Silverton/spawnpoints.lua" },
		{ name = "NewDenver_Connection_map", file = "media/maps/NewDenver_Connection_map/spawnpoints.lua" },
		{ name = "NewDenver_map", file = "media/maps/NewDenver_map/spawnpoints.lua" },
		{ name = "Rosebery_map", file = "media/maps/Rosebery_map/spawnpoints.lua" },
		{ name = "Silverton_map", file = "media/maps/Silverton_map/spawnpoints.lua" },
		{ name = "Barricaded Strip Mall - Reanimator", file = "media/maps/Barricaded Strip Mall - Reanimator/spawnpoints.lua" },
		{ name = "MonmouthCounty", file = "media/maps/MonmouthCounty/spawnpoints.lua" },
		{ name = "Ashenwood", file = "media/maps/Ashenwood/spawnpoints.lua" },
		{ name = "Fort Knox linked to Eerie Country", file = "media/maps/Fort Knox linked to Eerie Country/spawnpoints.lua" },
		{ name = "Near Fort Knox", file = "media/maps/Near Fort Knox/spawnpoints.lua" },
		{ name = "To Bedford Falls", file = "media/maps/To Bedford Falls/spawnpoints.lua" },
		{ name = "To Eerie Country", file = "media/maps/To Eerie Country/spawnpoints.lua" },
		{ name = "Eerie A", file = "media/maps/Eerie A/spawnpoints.lua" },
		{ name = "Eerie B", file = "media/maps/Eerie B/spawnpoints.lua" },
		{ name = "Eerie C", file = "media/maps/Eerie C/spawnpoints.lua" },
		{ name = "Eerie Country", file = "media/maps/Eerie Country/spawnpoints.lua" },
		{ name = "Eerie D", file = "media/maps/Eerie D/spawnpoints.lua" },
		{ name = "Eerie Country_map", file = "media/maps/Eerie Country_map/spawnpoints.lua" },
		{ name = "From Bedford Falls to Fort Knox", file = "media/maps/From Bedford Falls to Fort Knox/spawnpoints.lua" },
		{ name = "BedfordFalls", file = "media/maps/BedfordFalls/spawnpoints.lua" },
		{ name = "North", file = "media/maps/North/spawnpoints.lua" },
		{ name = "South", file = "media/maps/South/spawnpoints.lua" },
		{ name = "West", file = "media/maps/West/spawnpoints.lua" },
		{ name = "SaveOurStation_KnoxCountry_World", file = "media/maps/SaveOurStation_KnoxCountry_World/spawnpoints.lua" },
		{ name = "SecretZ_v2", file = "media/maps/SecretZ_v2/spawnpoints.lua" },
		{ name = "Checkpoint_2", file = "media/maps/Checkpoint_2/spawnpoints.lua" },
		{ name = "Checkpoint_3", file = "media/maps/Checkpoint_3/spawnpoints.lua" },
		{ name = "Checkpoint_4", file = "media/maps/Checkpoint_4/spawnpoints.lua" },
		{ name = "Checkpoint_5", file = "media/maps/Checkpoint_5/spawnpoints.lua" },
		{ name = "Checkpoint_6", file = "media/maps/Checkpoint_6/spawnpoints.lua" },
		{ name = "StBernardshill", file = "media/maps/StBernardshill/spawnpoints.lua" },
		{ name = "Trelai_4x4", file = "media/maps/Trelai_4x4/spawnpoints.lua" },
		{ name = "Trelai_spawns", file = "media/maps/Trelai_spawns/spawnpoints.lua" },
		{ name = "Fort Rock Ridge", file = "media/maps/Fort Rock Ridge/spawnpoints.lua" },
		{ name = "coryerdon", file = "media/maps/coryerdon/spawnpoints.lua" },
		{ name = "Wildberries", file = "media/maps/Wildberries/spawnpoints.lua" },
		{ name = "pz_rosewoodexp_map", file = "media/maps/pz_rosewoodexp_map/spawnpoints.lua" },
		{ name = "Zhukoniy Lighthouse Base", file = "media/maps/Zhukoniy Lighthouse Base/spawnpoints.lua" },
		{ name = "Xonics Mega Mall", file = "media/maps/Xonics Mega Mall/spawnpoints.lua" },
		{ name = "Xonics Mega Mall Exterior", file = "media/maps/Xonics Mega Mall Exterior/spawnpoints.lua" },
		{ name = "Xonics Mega Mall Interior", file = "media/maps/Xonics Mega Mall Interior/spawnpoints.lua" },
		{ name = "Xonics Mega Mall Roof", file = "media/maps/Xonics Mega Mall Roof/spawnpoints.lua" },
		{ name = "WestPointTrailerParkAndVhsStore", file = "media/maps/WestPointTrailerParkAndVhsStore/spawnpoints.lua" },
		{ name = "West Point Fire Department", file = "media/maps/West Point Fire Department/spawnpoints.lua" },
		{ name = "VSTOWN", file = "media/maps/VSTOWN/spawnpoints.lua" },
		{ name = "Tugaland", file = "media/maps/Tugaland/spawnpoints.lua" },
		{ name = "PrisonTWD", file = "media/maps/PrisonTWD/spawnpoints.lua" },
		{ name = "The Island", file = "media/maps/The Island/spawnpoints.lua" },
		{ name = "Rosewood VHS Store", file = "media/maps/Rosewood VHS Store/spawnpoints.lua" },
		{ name = "Northwest Blockade", file = "media/maps/Northwest Blockade/spawnpoints.lua" },
		{ name = "militaryairport", file = "media/maps/militaryairport/spawnpoints.lua" },
		{ name = "lighthouse", file = "media/maps/lighthouse/spawnpoints.lua" },
		{ name = "LaCasaDelLago", file = "media/maps/LaCasaDelLago/spawnpoints.lua" },
		{ name = "Irvington, KY", file = "media/maps/Irvington, KY/spawnpoints.lua" },
		{ name = "Irvington Road", file = "media/maps/Irvington Road/spawnpoints.lua" },
		{ name = "Hyrule County", file = "media/maps/Hyrule County/spawnpoints.lua" },
		{ name = "Hilltop", file = "media/maps/Hilltop/spawnpoints.lua" },
		{ name = "PZ_MyFarmhouse", file = "media/maps/PZ_MyFarmhouse/spawnpoints.lua" },
		{ name = "hq", file = "media/maps/hq/spawnpoints.lua" },
		{ name = "FrankfortKY", file = "media/maps/FrankfortKY/spawnpoints.lua" },
		{ name = "Firecamp", file = "media/maps/Firecamp/spawnpoints.lua" },
		{ name = "EdsAutoSalvage_NoFuel", file = "media/maps/EdsAutoSalvage_NoFuel/spawnpoints.lua" },
		{ name = "EZPZCenter", file = "media/maps/EZPZCenter/spawnpoints.lua" },
		{ name = "Riverdeltabase", file = "media/maps/Riverdeltabase/spawnpoints.lua" },
		{ name = "Dead in Hong Kong", file = "media/maps/Dead in Hong Kong/spawnpoints.lua" },
		{ name = "Cruise Ship in KY", file = "media/maps/Cruise Ship in KY/spawnpoints.lua" },
		{ name = "Westoutskirts-shippingCo", file = "media/maps/Westoutskirts-shippingCo/spawnpoints.lua" },
		{ name = "TrimbleCountyPowerStation", file = "media/maps/TrimbleCountyPowerStation/spawnpoints.lua" },
		{ name = "Riverwood", file = "media/maps/Riverwood/spawnpoints.lua" },
		{ name = "Refordville", file = "media/maps/Refordville/spawnpoints.lua" },
		{ name = "RavenCreek", file = "media/maps/RavenCreek/spawnpoints.lua" },
		{ name = "Pitstop", file = "media/maps/Pitstop/spawnpoints.lua" },
		{ name = "Otr", file = "media/maps/Otr/spawnpoints.lua" },
		{ name = "ParkingLot", file = "media/maps/ParkingLot/spawnpoints.lua" },
		{ name = "NewEkron", file = "media/maps/NewEkron/spawnpoints.lua" },
		{ name = "MREX", file = "media/maps/MREX/spawnpoints.lua" },
		{ name = "LittleTownship", file = "media/maps/LittleTownship/spawnpoints.lua" },
		{ name = "li_township", file = "media/maps/li_township/spawnpoints.lua" },
		{ name = "Kingsmouth", file = "media/maps/Kingsmouth/spawnpoints.lua" },
		{ name = "Greenleaf", file = "media/maps/Greenleaf/spawnpoints.lua" },
		{ name = "Grapeseed", file = "media/maps/Grapeseed/spawnpoints.lua" },
		{ name = "FortRedstone", file = "media/maps/FortRedstone/spawnpoints.lua" },
		{ name = "Fort Benning", file = "media/maps/Fort Benning/spawnpoints.lua" },
		{ name = "EVAC_Louisville", file = "media/maps/EVAC_Louisville/spawnpoints.lua" },
		{ name = "Chinatown_EX", file = "media/maps/Chinatown_EX/spawnpoints.lua" },
		{ name = "chernaville", file = "media/maps/chernaville/spawnpoints.lua" },
		{ name = "CONRTF", file = "media/maps/CONRTF/spawnpoints.lua" },
		{ name = "Blueberry", file = "media/maps/Blueberry/spawnpoints.lua" },
		{ name = "Blackwood", file = "media/maps/Blackwood/spawnpoints.lua" },
		{ name = "AZSpawn", file = "media/maps/AZSpawn/spawnpoints.lua" },
		{ name = "Skizots Vehicles Spawn Zones", file = "media/maps/Skizots Vehicles Spawn Zones/spawnpoints.lua" },
	}
end
